Server config choice
Apolline-Lille/apolline-flutter pull request #11
Opened 2022-01-27 11:39 UTC by RyanIkhlef

2022-01-31 21:48 UTC, Alystrasz commented
Regarding newest settings menu section design, do not hesitate taking all available screen space.

1. I think that we should have an entire subsection dedicated to backend configuration, so let's use separators.
2. Be careful with buttons, both should have same style and properly display inner text.
3. Since there's a lot of settings in this menu, maybe we should start adding subtitles to subsections?

--- 

<p align="center">

| <img height="600" src="https://user-images.githubusercontent.com/11993538/151877024-2e54c62d-f81e-4379-b214-0a7ff49040ea.png"> | <img height="600" src="https://user-images.githubusercontent.com/11993538/151878357-b2b60764-c9e1-43a6-a9f5-e34822651c34.png"> |
|:--:|:--:|
| *App screenshot* | *Quick mockup made on GIMP* |

</p>

2022-01-31 22:08 UTC, Alystrasz requested changes
There are some changes to translations that must be done, but great job overall!

2022-01-31 22:08 UTC, Alystrasz commented on apolline-flutter/lib/models/server_endpoint_handler.dart
> +    ServerModel defaultConfig = await SqfLiteService().getDefaultEndpoint(); // Si une configuration par defaut à déjà été enregistré, on la met sinon on met la config du fichier config_dev.json
Please write all code comments in English.

2022-02-01 12:30 UTC, RyanIkhlef commented on apolline-flutter/assets/translations/en-GB.json
> +    "codeTypeError": "You must to scan a QR code.",
It's shown when user scan an other type of code (bar code for example).

2022-02-01 15:45 UTC, Alystrasz approved these changes

2022-02-01 22:57 UTC, Alystrasz commented
Looks good to me.
You can increase minor version in `pubspec.yaml`, and if it works on iOS, I'll merge.

2022-02-02 15:16 UTC, merged